### ISSUE TITLE
add delay to health probes

### ISSUE THREAD

**Issue by jp83** [halkeye-helm-charts/tautulli#1]
I just pulled your helm chart which initially got stuck in a crash loop.  Seems it was killing it before it actually got up and running.  FYI, it worked when I tweaked the deployment to add 60sec initial delay and here's a snippet of the resulting yaml...

```
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /auth/login
            port: http
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: tautulli
        ports:
        - containerPort: 8181
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /auth/login
            port: http
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
```
